// <auto-generated />
using Factura.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Factura.Migrations
{
    [DbContext(typeof(FacturaDetailContext))]
    partial class FacturaDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Factura.Models.FacturaDetail", b =>
                {
                    b.Property<int>("CodFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodFactura"));

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<long>("Nit")
                        .HasColumnType("bigint");

                    b.HasKey("CodFactura");

                    b.ToTable("FacturaDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
