// <auto-generated />
using Colaborador.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colab.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20231003112524_Colab1")]
    partial class Colab1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Colaborador.Models.ColaboradorDetail", b =>
                {
                    b.Property<int>("CodColaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodColaborador"));

                    b.Property<string>("Apellido_1")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Apellido_2")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("CodGenero_FK")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long>("Dpi")
                        .HasColumnType("bigint");

                    b.Property<string>("FechaDeNacimiento")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Nombre_1")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nombre_2")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("CodColaborador");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("Colaborador.Models.Detalle_Colaborador_SectorDetail", b =>
                {
                    b.Property<int>("OmitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OmitId"));

                    b.Property<int>("CodColaborador_FK")
                        .HasColumnType("int");

                    b.Property<int>("CodSector_FK")
                        .HasColumnType("int");

                    b.Property<int>("CodTipoColaborador_FK")
                        .HasColumnType("int");

                    b.HasKey("OmitId");

                    b.ToTable("Detalle_Colaborador_Sector");
                });

            modelBuilder.Entity("Colaborador.Models.GeneroDetail", b =>
                {
                    b.Property<int>("CodGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodGenero"));

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("CodGenero");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("Colaborador.Models.SectorEmpresarialDetail", b =>
                {
                    b.Property<int>("CodSector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodSector"));

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("CodSector");

                    b.ToTable("SectorEmpresarial");
                });

            modelBuilder.Entity("Colaborador.Models.TipoColaborador", b =>
                {
                    b.Property<int>("CodTipoColaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipoColaborador"));

                    b.Property<string>("Colaborador")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("CodTipoColaborador");

                    b.ToTable("TipoColaborador");
                });
#pragma warning restore 612, 618
        }
    }
}
